spring.application.name=TeachView Website Backend

# Параметры подключения
spring.datasource.url=jdbc:postgresql://localhost:5432/teachview_db
spring.datasource.username=postgres
spring.datasource.password=password


# Создавать таблицы автоматически на основе Entity классов
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=teachview-super-secret-key-minimum-32-chars-long
jwt.expiration=86400000

# Лимит загружаемых файлов
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
